### ISSUE TITLE
S3 error `400 InvalidRequest - SOAP requests must be made over an HTTPS connection.`

### ISSUE THREAD

**Issue by 3y3** [mapbox/node-pre-gyp#131]
Hello, I trying to setup autopublishing for `node-inspector` submodule - `v8-debug`.
I don't have any problems with AppVeyor, but with Travis I have next error.

### From Travis log:
```log
node-pre-gyp@0.5.31 node_modules/node-pre-gyp
install.2
1.46s$ npm test
> v8-debug@0.3.2 test /home/travis/build/3y3/v8-debug
> mocha
  ․․․
  3 passing (10ms)
1.61s$ if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi;
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.5.31
node-pre-gyp info using node@0.10.33 | linux | x64
node-pre-gyp info package packing /home/travis/build/3y3/v8-debug/build/debug/v0.3.2/node-v11-linux-x64
node-pre-gyp info package packing /home/travis/build/3y3/v8-debug/build/debug/v0.3.2/node-v11-linux-x64/debug.node
node-pre-gyp info package Binary staged at "build/stage/debug/v0.3.2/node-v11-linux-x64.tar.gz"
node-pre-gyp ERR! publish error 
node-pre-gyp ERR! stack BadRequest: null
node-pre-gyp ERR! stack     at Request.extractError (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/services/s3.js:352:35)
node-pre-gyp ERR! stack     at Request.callListeners (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
node-pre-gyp ERR! stack     at Request.emit (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
node-pre-gyp ERR! stack     at Request.emit (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:604:14)
node-pre-gyp ERR! stack     at Request.transition (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:21:12)
node-pre-gyp ERR! stack     at AcceptorStateMachine.runTo (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/state_machine.js:14:12)
node-pre-gyp ERR! stack     at /home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/state_machine.js:26:10
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:22:9)
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/request.js:606:12)
node-pre-gyp ERR! stack     at Request.callListeners (/home/travis/build/3y3/v8-debug/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
node-pre-gyp ERR! System Linux 2.6.32-042stab090.5
node-pre-gyp ERR! command "node" "/home/travis/build/3y3/v8-debug/node_modules/.bin/node-pre-gyp" "package" "publish"
node-pre-gyp ERR! cwd /home/travis/build/3y3/v8-debug
node-pre-gyp ERR! node -v v0.10.33
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
null
```
### From S3 log:
```
5a2b5e5d590abed41d07774d8746a82b637b04c6640553bb755c7eff90d8ca42 
node-inspector [18/Dec/2014:15:36:48 +0000] 
199.182.120.7 - 0988E31AD9CDF4F0 REST.HEAD.OBJECT 
debug/v0.3.2/node-v11-linux-x64.tar.gz "HEAD /debug/v0.3.2/node-v11-linux-x64.tar.gz HTTP/1.1"
400 InvalidRequest 324 - 1 - "-" "aws-sdk-nodejs/2.0.31 linux/v0.10.33" -
```
### From S3 documentation:
`400 InvalidRequest - SOAP requests must be made over an HTTPS connection.`

I already updated to latest aws-sdk - same error.
This is reasonable for last stable (0.10.33 not 0.10.34 - this has error with certificates) and unstable node version.

My travis config:
```yml
language: cpp

compiler: gcc

os:
  - linux
  - osx

env:
  matrix:
    - export NODE_VERSION="0.10.33"
    - export NODE_VERSION="0.11.13"

before_install:
  - rm -rf ~/.nvm/ && git clone --depth 1 "https://github.com/creationix/nvm.git" ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - export PATH="./node_modules/.bin/:$PATH"
  - npm install -g node-gyp
  - PUBLISH_BINARY=false
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=true; fi;
  - platform=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
install:
  - npm install --build-from-source
  - npm test
before_script:
  - if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi;
  - node-pre-gyp clean
  - node-gyp clean
script:
  - INSTALL_RESULT=0
  - if [[ $PUBLISH_BINARY == true ]]; then
      INSTALL_RESULT=$(npm install --fallback-to-build=false > /dev/null)$? || true;
    fi;
  - if [[ $INSTALL_RESULT != 0 ]]; then node-pre-gyp unpublish; false; fi
  - node-pre-gyp clean
after_success:
  - node-pre-gyp info
```

Have you any experience with same error? Please help me...
