### ISSUE TITLE
node-pre-gyp Appveyor build failing for Windows x86 using Node 4.4.3

### ISSUE THREAD

**Issue by deadprogram** [mapbox/node-pre-gyp#209]
I was having trouble building for Windows x86 using Node.js 4.4.3, when I noticed that the Appveyor build for node-pre-gyp itself is failing for the same reason:

```
ENOENT: no such file or directory in readCAFile
```

The failed build can be seen here:

https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/1.0.373/job/h12w3ymhbyg6ltq6#L481

The build for Windows x64 using Node 4.4.3 succeeds, however.

I see that the node-gyp command is failing, but I thought perhaps node-pre-gyp might be missing something for the setup for the 4.4.3 release.

Any thoughts as to what is missing here? Now that 4.4.3 is the LTS version, it would be great to be able to have nice precompiled binaries for it.

Thank you!

**Comment by springmeyer** [comment]
This looks like something broken in node-gyp. node-gyp is failing in readCAFIle which recently was added in https://github.com/nodejs/node-gyp/pull/837 /cc @bnoordhuis

**Comment by bnoordhuis** [comment]
It looks like something (.npmrc? something in the environment?) is setting `npm_config_cafile` to the string `'undefined'`.

**Comment by reconbot** [comment]
Should this be filed on node-gyp itself?

**Comment by reconbot** [comment]
I've got a two step work around and I filed a bug with node-gyp.

The error we see is that the string `undefined` isn't a file. I'm only seeing this on 32bit windows machines with node 4.3 and 4.4. I haven't checked others.

The work around is to set the `cafile` option to a real file, I chose `package.json`. Then we get a second bug where even though it hasn't found a cert in package.json it still tries to use one. So you have to disable `strict-ssl `. We get some warnings but it works and doesn't seem to affect other node versions.

I added these to install phase in `appveyor.yml`
```yaml
  # work around an issue with node-gyp v3.3.1 and node 4x
  # package.json has no certificates in it so we're cool
  # https://github.com/nodejs/node-gyp/issues/921
  - cmd: npm config set -g cafile=package.json
  - cmd: npm config set -g strict-ssl=false
```
