### ISSUE TITLE
play nicer with travis caching of node_modules

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#40]
Travis.com supports caching node_modules between builds with:

``` yml
cache:
  directories:
    - node_modules
```

It appears this can break installs because node-pre-gyp does not rebuild (or test?) if a binary is found in place. Seen with v0.4.1
