### ISSUE TITLE
How to deal with multiple target?

### ISSUE THREAD

**Issue by MatthD** [mapbox/node-pre-gyp#482]
I currently have an electron project so that I should have electron as the target.

But I also have some native-module which will be use with node (for web pack -, have node-sass)

How to deal with those different targets with node-pre-gyp?

**Comment by idoodler** [comment]
I do have the same issue. I am able to build all targets, but anytime the CI/CI publishes the binary, only the current setup (macOS with node.js) is published.

Here is my `.gitlab-ci.yml`
```
stages:
  - build

build:
  stage: build
  tags:
    - nodeJS
    - nvm
  script:
    - export NODE_VERSION=`cat .nvmrc`
    - nvm install $NODE_VERSION
    - npm i
    # Use nvm exec $NODE_VERSION to execute the following command in the correct node environment
    - nvm exec $NODE_VERSION ./node_modules/.bin/node-pre-gyp install --build-from-source -target_platform=darwin --runtime=node
    - nvm exec $NODE_VERSION ./node_modules/.bin/node-pre-gyp install --build-from-source -target_platform=darwin --runtime=electron --target=9.1.0
    - nvm exec $NODE_VERSION ./node_modules/.bin/node-pre-gyp install --build-from-source -target_platform=win32 --runtime=node
    - nvm exec $NODE_VERSION ./node_modules/.bin/node-pre-gyp install --build-from-source -target_platform=win32 --runtime=electron --target=9.1.0
    - nvm exec $NODE_VERSION npm run publish-prebuild
  artifacts:
    name: nodesip
    paths:
      - lib/*
```

@MatthD Any Progress on your side?
